### ISSUE TITLE
"get_data.py" file is missing

### ISSUE THREAD

**Issue by jpzhangvincent** [alexcg1/jina-multimodal-fashion-search#13]
Can you upload the "get_data.py" script so we can fully reproduce the example? Thanks!

**Comment by alexcg1** [comment]
Here you go: https://github.com/alexcg1/fashion_docarray_push/

I haven't touched the code in a couple of months, so let me know if you hit any bugs

**Comment by alexcg1** [comment]
BTW, what are you building out of interest? Always curious to see what our community are up to!
