### ISSUE TITLE
I am having this error when i am trying to run the demo 

### ISSUE THREAD

**Issue by AhmetTpc** [alexcg1/jina-multimodal-fashion-search#6]
When i am searching via text, i am having this error in the background (console in the pycharm). In interface when I click the search button i get no result and this error pops up in the console.
  
 indexer@6717[E]:IndexError('list index out of range')
 add "--quiet-error" to suppress the exception details

Do you know a solution this error?

**Comment by alexcg1** [comment]
Sorry for the late reply.

I'll look into this next week. Seems my little search engine has been having a fair few bugs of late.

Since I revised the code after your issue, can you try again?

**Comment by AhmetTpc** [comment]
Sorry , I forgot to look issues side. I gave up on this project and i deleted my code. So ı can't try. Thanks for your help, ı found alternatives.
